"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const create_user_controller_1 = require("../controllers/create-user-controller");
const get_users_controller_1 = require("../controllers/get-users-controller");
const login_controller_1 = require("../controllers/login-controller");
const authMiddleware_1 = require("../middleware/authMiddleware");
const router = (0, express_1.Router)();
router.get('/users', authMiddleware_1.authJWT, get_users_controller_1.getUsers);
router.post('/create-user', create_user_controller_1.createUser);
router.post('/login', login_controller_1.loginUser);
exports.default = router;
